### ISSUE TITLE
Class Particle_Field

### ISSUE THREAD

**Issue by Juli-amo** [arabanus/DSAIIS-particle_life_2024#2]
This Class is supposed to represent the field in which all the particles are placed and react to one another.

It would be nice if this class has these functions:
- def prep_field (initializes the field)
- def simulate (simulates the particles and their reaction to one another)

**Comment by a-rabanus** [comment]
I have some OOP suggestions to make the project more "structured:

`prep_field` should return a list, dict or array of particle types, coordinates and starting speed
there should be a function `movement` that uses the `InteractionMatrix` and the positions from `prep_field` to return the next positions

**Comment by Juli-amo** [comment]
Hi everyone,

I’ve written some basic code for our particle_field class, but I believe we might need to revisit and redo parts of it since there are still many open questions.

> 

Here are some observations I made during the implementation process:

- **Visualization:** For now, visualizing the particle positions in a plot and updating it repeatedly works, but many similar projects skip this step and go straight to GUI-based visualization. This might be something to consider moving forward.

- **Movement Functions:** I’m unsure whether the particle movement logic should live in the Particle class or the ParticleField class. My preference is to keep all movement-related functionality in the ParticleField class. This way, it would be easier to incorporate input from the interaction matrix into each particle’s movement. It could also make future optimizations simpler.

- **Starting Point Generation:** I think it would be beneficial to move the function for generating particles' starting positions into the ParticleField class. This way, we can ensure particles are evenly distributed across the field. If we stick with the originally planned random generation, we might encounter issues like particles clustering too closely or being too far apart to interact effectively.

> 

Sorry for the delay I totally underestimated the complexity of this task and should have started way earlier! 
I promise it won't happen again 😊

**Comment by Juli-amo** [comment]
After our last team call on Wednesday, we agreed on the following changes:

- The movement function will be moved to the particle_field class.
- The start_movement function will also be moved to the particle_field class.
- The visualization of the particles and their movement will be moved to a new GUI class.

**Comment by Juli-amo** [comment]
I implemented the Particle Field class.
There are still a few questions open regarding the arguments that are given by the other classes and we will have to do some optimizing but they will be fixed in the next issues.
